on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verify git repository
          uses: actions/checkout@v2

        - name: Installing node with the version
          uses: actions/setup-node@v1
          with:
            node-version: 14


        - name: Dependencies install
          run: npm install

        - name: Lint executing for verify some errors
          run: npx eslint .